name: Report a bug / issue
description: Report an issue with ScoutBattle
labels: ["bug"]
assignees:
  - akhegr
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue
      description: >-
        Describe the issue you are experiencing here.
        Describe what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of ScoutBattle has the issue?
  - type: input
    attributes:
      label: What was the last working version of ScoutBattle?
      placeholder: core-
      description: >
        If known, otherwise leave blank.
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    validations:
      required: true
    attributes:
      label: Diagnostics information
      description: >-
        The shown error message, that the system returns
  - type: textarea
    attributes:
      label: Anything in the logs, that might be useful for me?
      description: Eg. how was the exception produced
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for me, use the field below.
  - type: markdown
    attributes:
      value: "Template created by @MTrab. Thank you."
